### ISSUE TITLE
请教大佬我直接clone的模型，在ubuntu系统运行的main.py报错，

### ISSUE THREAD

**Issue by Jasonx0123** [HuKai97/YOLOv5-LPRNet-Licence-Recognition#1]
运行ubuntu系统运行main.py，出现如下错误
Fusing layers... Model Summary: 140 layers, 7.24652e+06 parameters, 6.61683e+06 gradients
load det pretrained model successful!
load rec pretrained model successful!
image 1/4 demo/images/1.jpg: Traceback (most recent call last):
  File "/home/cv/Project/YOLOv5-LPRNet-Licence-Recognition-master/main.py", line 175, in <module>
    detect()
  File "/home/cv/Project/YOLOv5-LPRNet-Licence-Recognition-master/main.py", line 113, in detect
    im0 = plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3)
  File "/home/cv/Project/YOLOv5-LPRNet-Licence-Recognition-master/utils/utils.py", line 969, in plot_one_box
    image=change_cv2_draw(img,label,(int(c1[0]), int(c1[1]) - 30),5,[225,225,225])
  File "/home/cv/Project/YOLOv5-LPRNet-Licence-Recognition-master/utils/utils.py", line 953, in change_cv2_draw
    font = ImageFont.truetype("simsun.ttc", 32, encoding="unic")
  File "/home/cv/anaconda3/envs/yolov5/lib/python3.8/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/home/cv/anaconda3/envs/yolov5/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/cv/anaconda3/envs/yolov5/lib/python3.8/site-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource
请教亲应该怎么解决呢？

**Comment by HuKai97** [comment]
网上下个simsun.ttc放在root下

**Comment by HuKai97** [comment]
https://blog.csdn.net/weixin_60177957/article/details/122589489

**Comment by Jasonx0123** [comment]
>万分感谢

**Comment by HuKai97** [comment]
或者看这个博客说的换一下字体

**Comment by Jasonx0123** [comment]
> 或者看这个博客说的换一下字体

好的 谢谢 我搞一下

**Comment by Jasonx0123** [comment]
> simsun.ttc
成功啦，谢谢大佬，我把simsun.ttc放到了当前目录下

**Comment by HuKai97** [comment]
ok
